#!/bin/bash
#
# Handle all WordPress related commands.

function continue_wordpress_setup
{
  local project_name=$1
  local virtual_host=$2
  local project_path="projects/${project_name}"
  local host_sql_path="database/${DB_NAME}.sql"
  local sql_path="/tmp/migrations/${DB_NAME}.sql"

  cp core/configs/default/configs/wp-config.php ${project_path}/wp-config.php

  if [[ -r "${host_sql_path}" ]]; then
    info "Importing ${host_sql_path}"

    docker exec -it wpdev-mysql bash -c "mysql ${DB_NAME} < ${sql_path}" || \
      error "Unable to import ${DB_NAME}.sql"
  else
    install_core ${project_name} ${virtual_host}
  fi

  install_plugins ${project_name} ${virtual_host}
  install_themes ${project_name} ${virtual_host}
}

function install_core
{
  local project_name=$1
  local virtual_host=$2

  local url=$(get_yaml_value ${project_name}.host)
  local title=$(get_value ${project_name}.title ${WP_DEFAULT_TITLE})
  local admin_user=$(get_value ${project_name}.admin_user ${WP_ADMIN_USER})
  local admin_password=$(get_value ${project_name}.admin_password ${WP_ADMIN_PASSWORD})
  local admin_email=$(get_value ${project_name}.admin_email ${WP_ADMIN_EMAIL})

  local install_cmd="wp core install --url=\"${url}\" --title=\"${title}\" --admin_user=\"${admin_user}\" --admin_password=\"${admin_password}\" --admin_email=\"${admin_email}\" --skip-email --allow-root";

  info "Installing core"
  docker exec -it ${virtual_host} bash -c "${install_cmd}"
}

function install_plugins
{
  local project_name=$1
  local virtual_host=$2
  local plugins=$(get_yaml_values ${project_name}.plugins 2> /dev/null)

  if [[ -n "${plugins}" ]]; then
    info "Installing plugins"

    IFS=$'\n'
    for plugin in ${plugins}; do
      docker exec -it ${virtual_host} bash -c "wp plugin install ${plugin} --allow-root"
    done
    unset IFS
  fi
}

function install_themes
{
  local project_name=$1
  local virtual_host=$2
  local themes=$(get_yaml_values ${project_name}.themes 2> /dev/null)

  if [[ -n "${themes}" ]]; then
    info "Installing themes"

    IFS=$'\n'
    for theme in ${themes}; do
      docker exec -it ${virtual_host} bash -c "wp theme install ${theme} --allow-root"
    done
    unset IFS
  fi
}
